"""The historical scan file, in Spark.

    spark-submit history_job.py

`data/scans_history.csv` is eleven months of scans - about 285,000 rows and 18 MB.
That is not big data and it is not meant to be. It is large enough that the
things Spark makes you decide start to matter, and small enough to finish while
you watch.

Run it from this folder. On Windows, use the environment from Lecture 11 -
JAVA_HOME, HADOOP_HOME and winutils - not a fresh install.
"""

import os
import sys
import glob

# Ensure Windows Spark environment from Lecture 11 is active
if "JAVA_HOME" not in os.environ:
    os.environ["JAVA_HOME"] = r"C:\Program Files\Eclipse Adoptium\jdk-17.0.20.101-hotspot"
if "HADOOP_HOME" not in os.environ:
    os.environ["HADOOP_HOME"] = r"C:\Users\HP\Data Engineering\Lecture_11_Spark_Foundations\hadoop"

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, to_timestamp, to_date, date_format, broadcast, count, when, round
)
from pyspark.sql.types import (
    StructType, StructField, LongType, IntegerType, DoubleType, StringType
)

spark = (SparkSession.builder
         .appName("waseet-history")
         .master("local[*]")
         .getOrCreate())

spark.sparkContext.setLogLevel("WARN")

# 1. An explicit schema. Avoids costly double-pass of inferSchema.
SCHEMA = StructType([
    StructField("scan_id", LongType(), False),
    StructField("parcel_id", LongType(), False),
    StructField("customer_id", IntegerType(), False),
    StructField("scanned_at", StringType(), False),
    StructField("hub_id", IntegerType(), False),
    StructField("courier_id", IntegerType(), True),
    StructField("scan_type", StringType(), False),
    StructField("weight_kg", DoubleType(), False),
    StructField("service_code", StringType(), False),
])

DATA_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "data"))
history_path = os.path.join(DATA_DIR, "scans_history.csv")
hubs_path = os.path.join(DATA_DIR, "hubs.csv")
services_path = os.path.join(DATA_DIR, "service_levels.csv")

# 2. Read scans_history.csv with explicit schema
history = spark.read.schema(SCHEMA).option("header", "true").csv(history_path)
print(f"Loaded history records: {history.count()}")

# Read lookup tables
hubs = spark.read.option("header", "true").option("inferSchema", "true").csv(hubs_path)
services = spark.read.option("header", "true").option("inferSchema", "true").csv(services_path)

# 3. Shape it:
#    - parse scanned_at
#    - derive scan_date for partitioning
#    - broadcast join hubs for region and service_levels for promised_hours
#    - drop unneeded redundant columns
shaped = (history
          .withColumn("scanned_at", to_timestamp(col("scanned_at"), "yyyy-MM-dd HH:mm:ss"))
          .withColumn("scan_date", to_date(col("scanned_at"))))

# Join hubs (10 rows) using broadcast to eliminate network shuffling of 285,000 history rows
curated = (shaped
           .join(broadcast(hubs.select("hub_id", "hub_name", "region")), on="hub_id", how="inner")
           .join(broadcast(services.select("service_code", "promised_hours")), on="service_code", how="inner"))

print("\n--- Physical Execution Plan for Broadcast Joins ---")
curated.explain()

# 4. Aggregations:
#    - scans per hub per day
daily_hub_scans = (curated
                   .groupBy("scan_date", "hub_id", "hub_name", "region")
                   .agg(count("scan_id").alias("scan_count"))
                   .orderBy("scan_date", "hub_id"))

print("\n--- Scans per Hub per Day (Sample) ---")
daily_hub_scans.show(10, truncate=False)

#    - share of DELIVERED vs FAILED per region per month
status_monthly = (curated
                  .filter(col("scan_type").isin("DELIVERED", "FAILED"))
                  .withColumn("scan_month", date_format(col("scanned_at"), "yyyy-MM"))
                  .groupBy("region", "scan_month")
                  .agg(
                      count(when(col("scan_type") == "DELIVERED", 1)).alias("delivered_count"),
                      count(when(col("scan_type") == "FAILED", 1)).alias("failed_count"),
                      count("scan_id").alias("total_terminal_scans")
                  )
                  .withColumn("delivered_pct", round(col("delivered_count") * 100.0 / col("total_terminal_scans"), 2))
                  .withColumn("failed_pct", round(col("failed_count") * 100.0 / col("total_terminal_scans"), 2))
                  .orderBy("scan_month", "region"))

print("\n--- DELIVERED vs FAILED Share per Region per Month ---")
status_monthly.show(20, truncate=False)

# 5. Write curated zone as Parquet, partitioned by scan_date
output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "curated", "scans"))
print(f"\nWriting curated dataset to: {output_dir}")
curated.write.mode("overwrite").partitionBy("scan_date").parquet(output_dir)

# Inspect file count generated by partitioned write
parquet_files = glob.glob(os.path.join(output_dir, "**", "*.parquet"), recursive=True)
date_partitions = glob.glob(os.path.join(output_dir, "scan_date=*"))
print(f"Total date partitions created: {len(date_partitions)}")
print(f"Total Parquet data files written: {len(parquet_files)}")
print(f"Average files per partition: {len(parquet_files) / max(len(date_partitions), 1):.2f}")

spark.stop()

